pip3 install -U nltk
pip3 install -U spacy
pip3 install -U flask
pip3 install -U flask_cors
pip3 install -U Flask-Excel
pip3 install -U parsedatetime
pip3 install -U requests
pip3 install -U sklearn
pip3 install -U pymongo
pip3 install -U tensorflow
